// Fallout 3 Location Database
// Coordinates are relative (0-1) on the 658x663 map

const CATEGORIES = {
    vaults: { name: 'Vaults', icon: 'icon_0065.jpg', color: '#14fe17' },
    metro: { name: 'Metro Stations', icon: 'icon_0068.jpg', color: '#14fe17' },
    settlements: { name: 'Settlements', icon: 'icon_0071.jpg', color: '#14fe17' },
    caves: { name: 'Caves', icon: 'icon_0074.jpg', color: '#14fe17' },
    cities: { name: 'Cities/Ruins', icon: 'icon_0077.jpg', color: '#14fe17' },
    factories: { name: 'Factories', icon: 'icon_0080.jpg', color: '#14fe17' },
    military: { name: 'Military', icon: 'icon_0083.jpg', color: '#14fe17' },
    monuments: { name: 'Monuments', icon: 'icon_0086.jpg', color: '#14fe17' },
    natural: { name: 'Landmarks', icon: 'icon_0089.jpg', color: '#14fe17' },
    sewers: { name: 'Sewers', icon: 'icon_0092.jpg', color: '#14fe17' },
    towns: { name: 'Towns', icon: 'icon_0095.jpg', color: '#14fe17' },
    urban: { name: 'Urban', icon: 'icon_0098.jpg', color: '#14fe17' },
    doors: { name: 'Entrances', icon: 'icon_0101.jpg', color: '#14fe17' },
    undiscovered: { name: 'Unmarked', icon: 'icon_0104.jpg', color: '#666666' }
};

const COLLECTIBLE_CATEGORIES = {
    bobbleheads_special: { name: 'S.P.E.C.I.A.L. Bobbleheads', color: '#ffd700' },
    bobbleheads_skills: { name: 'Skills Bobbleheads', color: '#ffd700' },
    skillbooks: { name: 'Skill Books', color: '#87ceeb' }
};

// Main location data
const locations = [
    // === VAULTS ===
    { id: 1, name: 'Vault 101', category: 'vaults', x: 0.23, y: 0.58,
      description: 'Your home vault and starting location. A sealed community that has not opened since the Great War.',
      image: 'img_0563.jpg' },
    { id: 2, name: 'Vault 106', category: 'vaults', x: 0.18, y: 0.42,
      description: 'An experimental vault where psychoactive drugs were pumped into the air supply. Beware of crazed survivors.',
      image: 'img_0567.jpg' },
    { id: 3, name: 'Vault 108', category: 'vaults', x: 0.62, y: 0.22,
      description: 'Home to the Gary clones. All inhabitants are hostile clones named Gary.',
      image: 'img_0570.jpg' },
    { id: 4, name: 'Vault 87', category: 'vaults', x: 0.25, y: 0.24,
      description: 'The source of the Capital Wasteland Super Mutants. Accessible only through Little Lamplight.',
      image: 'img_0575.jpg' },
    { id: 5, name: 'Vault 92', category: 'vaults', x: 0.72, y: 0.12,
      description: 'A vault for musicians where white noise experiments drove residents insane.',
      image: 'img_0579.jpg' },
    { id: 6, name: 'Vault 112', category: 'vaults', x: 0.15, y: 0.78,
      description: 'Location of Tranquility Lane virtual reality simulation. Your father is trapped here.',
      image: 'img_0582.jpg' },
    { id: 7, name: 'Vault-Tec HQ', category: 'vaults', x: 0.55, y: 0.62,
      description: 'Corporate headquarters of Vault-Tec in downtown DC. Contains the Perception Bobblehead.',
      image: 'img_0585.jpg' },

    // === MAJOR SETTLEMENTS ===
    { id: 10, name: 'Megaton', category: 'settlements', x: 0.27, y: 0.61,
      description: 'A fortified town built around an undetonated atomic bomb. Major trading hub and home to Moira Brown.',
      image: 'img_0590.jpg' },
    { id: 11, name: 'Rivet City', category: 'settlements', x: 0.72, y: 0.78,
      description: 'The largest human settlement, built on a beached aircraft carrier. Home to Dr. Li and the science team.',
      image: 'img_0594.jpg' },
    { id: 12, name: 'Tenpenny Tower', category: 'settlements', x: 0.08, y: 0.82,
      description: 'A luxurious hotel for the wealthy elite, run by Allistair Tenpenny.',
      image: 'img_0597.jpg' },
    { id: 13, name: 'Underworld', category: 'settlements', x: 0.56, y: 0.58,
      description: 'A ghoul city located in the Museum of History. Peaceful community.',
      image: 'img_0602.jpg' },
    { id: 14, name: 'Paradise Falls', category: 'settlements', x: 0.42, y: 0.15,
      description: 'Headquarters of the slavers. A dangerous place for the unprepared.',
      image: 'img_0606.jpg' },
    { id: 15, name: 'Canterbury Commons', category: 'settlements', x: 0.72, y: 0.28,
      description: 'A trading hub and home to Uncle Roe. Witness the battle of the mechanist vs antagonizer.',
      image: 'img_0609.jpg' },
    { id: 16, name: 'Big Town', category: 'settlements', x: 0.48, y: 0.35,
      description: 'Settlement of former Little Lamplight residents. Constantly under super mutant attack.',
      image: 'img_0612.jpg' },
    { id: 17, name: 'Arefu', category: 'settlements', x: 0.35, y: 0.38,
      description: 'A small settlement on an overpass, terrorized by the Family.',
      image: 'img_0617.jpg' },
    { id: 18, name: 'Grayditch', category: 'settlements', x: 0.45, y: 0.72,
      description: 'A town overrun by fire ants. Home to a young boy named Bryan Wilks.',
      image: 'img_0621.jpg' },
    { id: 19, name: 'Republic of Dave', category: 'settlements', x: 0.92, y: 0.08,
      description: 'A tiny "nation" in the far northeast ruled by President Dave.',
      image: 'img_0626.jpg' },
    { id: 20, name: 'Little Lamplight', category: 'settlements', x: 0.22, y: 0.26,
      description: 'A cave settlement run entirely by children. Only entrance to Vault 87.',
      image: 'img_0629.jpg' },
    { id: 21, name: 'Oasis', category: 'settlements', x: 0.55, y: 0.08,
      description: 'A hidden grove of living trees, home to the Treeminders and Harold.',
      image: 'img_0634.jpg' },
    { id: 22, name: 'Andale', category: 'settlements', x: 0.32, y: 0.88,
      description: 'A seemingly normal pre-war town with a dark secret.',
      image: 'img_0638.jpg' },
    { id: 23, name: 'Girdershade', category: 'towns', x: 0.18, y: 0.85,
      description: 'A tiny settlement of two people, Sierra and Ronald.',
      image: 'img_0641.jpg' },
    { id: 24, name: 'Minefield', category: 'towns', x: 0.58, y: 0.28,
      description: 'An abandoned town rigged with explosives and guarded by Arkansas.',
      image: 'img_0644.jpg' },

    // === KEY LANDMARKS ===
    { id: 30, name: 'Galaxy News Radio', category: 'monuments', x: 0.50, y: 0.52,
      description: 'Broadcasting station of Three Dog, voice of the wasteland. Located in Chevy Chase.',
      image: 'img_0649.jpg' },
    { id: 31, name: 'The Citadel', category: 'military', x: 0.62, y: 0.72,
      description: 'Brotherhood of Steel headquarters built in the ruins of the Pentagon.',
      image: 'img_0653.jpg' },
    { id: 32, name: 'Jefferson Memorial', category: 'monuments', x: 0.65, y: 0.68,
      description: 'Project Purity\'s location. Your father\'s life work to purify the Potomac.',
      image: 'img_0656.jpg' },
    { id: 33, name: 'Washington Monument', category: 'monuments', x: 0.55, y: 0.60,
      description: 'The famous obelisk, now used as a Brotherhood outpost.',
      image: 'img_0661.jpg' },
    { id: 34, name: 'Capitol Building', category: 'monuments', x: 0.60, y: 0.62,
      description: 'The former seat of US government, now a super mutant stronghold.',
      image: 'img_0664.jpg' },
    { id: 35, name: 'Lincoln Memorial', category: 'monuments', x: 0.52, y: 0.62,
      description: 'Former memorial to Lincoln, contested between slavers and abolitionists.',
      image: 'img_0667.jpg' },
    { id: 36, name: 'Museum of History', category: 'monuments', x: 0.56, y: 0.58,
      description: 'Houses the Underworld ghoul settlement and historical exhibits.',
      image: 'img_0672.jpg' },
    { id: 37, name: 'Museum of Technology', category: 'monuments', x: 0.54, y: 0.58,
      description: 'Contains the Virgo II lunar lander dish needed for GNR quest.',
      image: 'img_0675.jpg' },
    { id: 38, name: 'National Archives', category: 'monuments', x: 0.58, y: 0.60,
      description: 'Repository of historical documents. Contains the Declaration of Independence.',
      image: 'img_0680.jpg' },

    // === MILITARY LOCATIONS ===
    { id: 40, name: 'Fort Bannister', category: 'military', x: 0.18, y: 0.72,
      description: 'Talon Company headquarters. Heavily fortified mercenary base.',
      image: 'img_0684.jpg' },
    { id: 41, name: 'Fort Constantine', category: 'military', x: 0.22, y: 0.10,
      description: 'Pre-war military base with T-51b Power Armor in the bunker.',
      image: 'img_0689.jpg' },
    { id: 42, name: 'Fort Independence', category: 'military', x: 0.30, y: 0.85,
      description: 'Outcast Brotherhood base. Trade tech for supplies here.',
      image: 'img_0692.jpg' },
    { id: 43, name: 'National Guard Depot', category: 'military', x: 0.68, y: 0.38,
      description: 'Military depot with experimental weapons. Contains the Keller Family recordings.',
      image: 'img_0697.jpg' },
    { id: 44, name: 'SatCom Array NW-05a', category: 'military', x: 0.18, y: 0.12,
      description: 'Satellite communication array. Raiders and valuable tech.',
      image: 'img_0700.jpg' },
    { id: 45, name: 'SatCom Array NN-03d', category: 'military', x: 0.35, y: 0.05,
      description: 'Another satellite array north of Fort Constantine.',
      image: 'img_0703.jpg' },
    { id: 46, name: 'SatCom Array NW-07c', category: 'military', x: 0.12, y: 0.18,
      description: 'Westernmost satellite array installation.',
      image: 'img_0708.jpg' },
    { id: 47, name: 'Raven Rock', category: 'military', x: 0.15, y: 0.15,
      description: 'Secret Enclave base hidden in the mountains. Accessible late in the main quest.',
      image: 'img_0712.jpg' },
    { id: 48, name: 'Adams Air Force Base', category: 'military', x: 0.88, y: 0.82,
      description: 'Enclave mobile base. Final location in Broken Steel DLC.',
      image: 'img_0717.jpg' },

    // === FACTORIES ===
    { id: 50, name: 'Nuka-Cola Plant', category: 'factories', x: 0.28, y: 0.95,
      description: 'The pre-war Nuka-Cola bottling facility. Source of Nuka-Cola Quantum.',
      image: 'img_0720.jpg' },
    { id: 51, name: 'RobCo Facility', category: 'factories', x: 0.32, y: 0.68,
      description: 'Robot manufacturing plant. Lots of hostile robots inside.',
      image: 'img_0725.jpg' },
    { id: 52, name: 'Corvega Factory', category: 'factories', x: 0.68, y: 0.40,
      description: 'Pre-war automobile manufacturing plant. Raider occupied.',
      image: 'img_0728.jpg' },
    { id: 53, name: 'Red Racer Factory', category: 'factories', x: 0.22, y: 0.75,
      description: 'Tricycle factory. Contains unique melee weapon.',
      image: 'img_0733.jpg' },
    { id: 54, name: 'MDPL Mass Relay Station', category: 'factories', x: 0.50, y: 0.12,
      description: 'Power relay station in the north.',
      image: 'img_0736.jpg' },
    { id: 55, name: 'MDPL-13 Power Station', category: 'factories', x: 0.65, y: 0.08,
      description: 'Another power station in the far north.',
      image: 'img_0741.jpg' },
    { id: 56, name: 'Chryslus Building', category: 'factories', x: 0.55, y: 0.40,
      description: 'Pre-war Chryslus Motors corporate headquarters. Super mutant infested.',
      image: 'img_0744.jpg' },
    { id: 57, name: 'Hubris Comics', category: 'factories', x: 0.52, y: 0.55,
      description: 'Comic book publisher HQ. Ghouls and the Grognak costume.',
      image: 'img_0749.jpg' },

    // === CAVES & NATURAL ===
    { id: 60, name: 'Yao Guai Tunnels', category: 'caves', x: 0.10, y: 0.52,
      description: 'Dangerous cave system filled with Yao Guai bears.',
      image: 'img_0752.jpg' },
    { id: 61, name: 'Deathclaw Sanctuary', category: 'caves', x: 0.12, y: 0.35,
      description: 'The most dangerous location in the wasteland. Home to many Deathclaws.',
      image: 'img_0757.jpg' },
    { id: 62, name: 'Cliffside Cavern', category: 'caves', x: 0.05, y: 0.60,
      description: 'Raider cave hideout on the western edge of the map.',
      image: 'img_0760.jpg' },
    { id: 63, name: 'Rockbreaker\'s Last Gas', category: 'natural', x: 0.08, y: 0.45,
      description: 'Abandoned gas station. Deathclaws nearby.',
      image: 'img_0563.jpg' },
    { id: 64, name: 'Everglow National Campground', category: 'natural', x: 0.10, y: 0.60,
      description: 'Pre-war campground, now inhabited by raiders.',
      image: 'img_0567.jpg' },
    { id: 65, name: 'Agatha\'s House', category: 'natural', x: 0.58, y: 0.18,
      description: 'Home of Agatha, an elderly violinist. Quest giver.',
      image: 'img_0570.jpg' },
    { id: 66, name: 'Scrapyard', category: 'natural', x: 0.52, y: 0.38,
      description: 'Location where you can find the dog companion Dogmeat.',
      image: 'img_0575.jpg' },

    // === METRO STATIONS ===
    { id: 70, name: 'Farragut West Station', category: 'metro', x: 0.52, y: 0.60,
      description: 'Metro station connecting to multiple areas. Feral ghouls inside.',
      image: 'img_0579.jpg' },
    { id: 71, name: 'Metro Central', category: 'metro', x: 0.54, y: 0.62,
      description: 'Central hub of the DC Metro system.',
      image: 'img_0582.jpg' },
    { id: 72, name: 'Anacostia Crossing', category: 'metro', x: 0.68, y: 0.72,
      description: 'Metro station near Rivet City.',
      image: 'img_0585.jpg' },
    { id: 73, name: 'Museum Station', category: 'metro', x: 0.55, y: 0.58,
      description: 'Station connecting to the Mall museums.',
      image: 'img_0590.jpg' },
    { id: 74, name: 'Friendship Heights', category: 'metro', x: 0.46, y: 0.50,
      description: 'Northern DC metro access point.',
      image: 'img_0594.jpg' },
    { id: 75, name: 'Tenleytown Station', category: 'metro', x: 0.48, y: 0.48,
      description: 'Metro station in the Chevy Chase area.',
      image: 'img_0597.jpg' },
    { id: 76, name: 'Foggy Bottom Station', category: 'metro', x: 0.50, y: 0.58,
      description: 'Western DC metro access.',
      image: 'img_0602.jpg' },
    { id: 77, name: 'Dupont Circle Station', category: 'metro', x: 0.52, y: 0.55,
      description: 'Station with access to Dupont Circle area.',
      image: 'img_0606.jpg' },
    { id: 78, name: 'Georgetown Metro', category: 'metro', x: 0.48, y: 0.58,
      description: 'Access to Georgetown/West DC.',
      image: 'img_0609.jpg' },
    { id: 79, name: 'Penn Ave Georgetown Metro', category: 'metro', x: 0.50, y: 0.60,
      description: 'Pennsylvania Avenue metro access.',
      image: 'img_0612.jpg' },
    { id: 80, name: 'Arlington Cemetery', category: 'metro', x: 0.58, y: 0.68,
      description: 'Cemetery metro station near the Citadel.',
      image: 'img_0617.jpg' },

    // === URBAN/CITY RUINS ===
    { id: 90, name: 'Chevy Chase', category: 'urban', x: 0.48, y: 0.52,
      description: 'Urban ruins northwest of DC. Path to GNR building.',
      image: 'img_0621.jpg' },
    { id: 91, name: 'Georgetown', category: 'urban', x: 0.46, y: 0.58,
      description: 'Ruined urban area with super mutants.',
      image: 'img_0626.jpg' },
    { id: 92, name: 'Dupont Circle', category: 'urban', x: 0.52, y: 0.54,
      description: 'DC neighborhood ruins.',
      image: 'img_0629.jpg' },
    { id: 93, name: 'Vernon Square', category: 'urban', x: 0.54, y: 0.52,
      description: 'Urban area near the Mall.',
      image: 'img_0634.jpg' },
    { id: 94, name: 'Pennsylvania Avenue', category: 'urban', x: 0.56, y: 0.60,
      description: 'Historic avenue leading to the Capitol.',
      image: 'img_0638.jpg' },
    { id: 95, name: 'The Mall', category: 'urban', x: 0.55, y: 0.60,
      description: 'The National Mall, heavily contested by super mutants and the Brotherhood.',
      image: 'img_0641.jpg' },
    { id: 96, name: 'Seward Square', category: 'urban', x: 0.62, y: 0.64,
      description: 'Eastern DC urban area.',
      image: 'img_0644.jpg' },
    { id: 97, name: 'Takoma Park', category: 'urban', x: 0.58, y: 0.42,
      description: 'Northern urban ruins with the Behemoth.',
      image: 'img_0649.jpg' },
    { id: 98, name: 'Falls Church', category: 'urban', x: 0.40, y: 0.58,
      description: 'Suburban ruins west of DC.',
      image: 'img_0653.jpg' },
    { id: 99, name: 'Fairfax Ruins', category: 'urban', x: 0.35, y: 0.68,
      description: 'Suburban area with raider presence.',
      image: 'img_0656.jpg' },
    { id: 100, name: 'Springvale', category: 'urban', x: 0.25, y: 0.58,
      description: 'Ruined town near Vault 101 and Megaton.',
      image: 'img_0661.jpg' },

    // === ADDITIONAL LOCATIONS ===
    { id: 110, name: 'Evergreen Mills', category: 'towns', x: 0.15, y: 0.68,
      description: 'Major raider encampment with a captive super mutant behemoth.',
      image: 'img_0664.jpg' },
    { id: 111, name: 'Meresti Trainyard', category: 'towns', x: 0.40, y: 0.40,
      description: 'Entrance to Meresti Metro Station and The Family.',
      image: 'img_0667.jpg' },
    { id: 112, name: 'Greener Pastures Disposal', category: 'natural', x: 0.75, y: 0.18,
      description: 'Radioactive waste disposal site. Very irradiated.',
      image: 'img_0672.jpg' },
    { id: 113, name: 'Old Olney', category: 'towns', x: 0.70, y: 0.20,
      description: 'Deathclaw infested town. Extremely dangerous.',
      image: 'img_0675.jpg' },
    { id: 114, name: 'Wheaton Armory', category: 'military', x: 0.60, y: 0.35,
      description: 'National Guard armory with weapons cache.',
      image: 'img_0680.jpg' },
    { id: 115, name: 'Germantown Police HQ', category: 'cities', x: 0.45, y: 0.32,
      description: 'Police headquarters overrun by super mutants. Big Town residents held here.',
      image: 'img_0684.jpg' },
    { id: 116, name: 'Hamilton\'s Hideaway', category: 'caves', x: 0.38, y: 0.45,
      description: 'Small cave with raider inhabitants.',
      image: 'img_0689.jpg' },
    { id: 117, name: 'Broadcast Tower KB5', category: 'natural', x: 0.45, y: 0.25,
      description: 'Radio tower broadcasting encrypted signals.',
      image: 'img_0692.jpg' },
    { id: 118, name: 'Broadcast Tower LP8', category: 'natural', x: 0.28, y: 0.48,
      description: 'Another radio broadcast tower.',
      image: 'img_0697.jpg' },
    { id: 119, name: 'Broadcast Tower KT8', category: 'natural', x: 0.12, y: 0.72,
      description: 'Radio tower in the southwestern region.',
      image: 'img_0700.jpg' },
    { id: 120, name: 'Dunwich Building', category: 'cities', x: 0.10, y: 0.92,
      description: 'Haunted office building with Lovecraftian horror elements.',
      image: 'img_0703.jpg' },
    { id: 121, name: 'L.O.B. Enterprises', category: 'factories', x: 0.40, y: 0.70,
      description: 'Corporate building with protectron assembly line.',
      image: 'img_0708.jpg' },
    { id: 122, name: 'Mason Dixon Salvage', category: 'natural', x: 0.05, y: 0.85,
      description: 'Salvage yard at the edge of the map.',
      image: 'img_0712.jpg' },
    { id: 123, name: 'Hallowed Moors Cemetery', category: 'natural', x: 0.52, y: 0.30,
      description: 'Pre-war cemetery, now full of ghouls.',
      image: 'img_0717.jpg' },
    { id: 124, name: 'Jalbert Brothers Waste Disposal', category: 'natural', x: 0.68, y: 0.48,
      description: 'Hazardous waste site with barrels of radioactive material.',
      image: 'img_0720.jpg' },
    { id: 125, name: 'Temple of the Union', category: 'settlements', x: 0.78, y: 0.25,
      description: 'Hideout for escaped slaves planning their freedom.',
      image: 'img_0725.jpg' },
    { id: 126, name: 'Reclining Groves Resort Homes', category: 'towns', x: 0.78, y: 0.18,
      description: 'Pre-war resort area, now abandoned.',
      image: 'img_0728.jpg' },
    { id: 127, name: 'WKML Broadcast Station', category: 'natural', x: 0.75, y: 0.35,
      description: 'Radio station with Talon Company presence.',
      image: 'img_0733.jpg' },
    { id: 128, name: 'Jury Street Metro Station', category: 'metro', x: 0.38, y: 0.52,
      description: 'Metro station west of DC proper.',
      image: 'img_0736.jpg' },
    { id: 129, name: 'Roosevelt Academy', category: 'cities', x: 0.45, y: 0.25,
      description: 'Pre-war school now occupied by raiders.',
      image: 'img_0741.jpg' },
    { id: 130, name: 'Charnel House', category: 'undiscovered', x: 0.70, y: 0.15,
      description: 'Unmarked horror location near Old Olney.',
      image: 'img_0744.jpg' },

    // === SEWERS ===
    { id: 140, name: 'County Sewer Mainline', category: 'sewers', x: 0.32, y: 0.62,
      description: 'Sewer access point with feral ghouls.',
      image: 'img_0749.jpg' },
    { id: 141, name: 'Tepid Sewers', category: 'sewers', x: 0.75, y: 0.70,
      description: 'Sewer system entrance near Rivet City.',
      image: 'img_0752.jpg' },
    { id: 142, name: 'Flooded Metro', category: 'sewers', x: 0.70, y: 0.65,
      description: 'Partially flooded metro tunnels with mirelurks.',
      image: 'img_0757.jpg' },
    { id: 143, name: 'Irradiated Metro', category: 'sewers', x: 0.62, y: 0.60,
      description: 'Highly radioactive metro section.',
      image: 'img_0760.jpg' },

    // === DOORS/ENTRANCES ===
    { id: 150, name: 'Megaton Gate', category: 'doors', x: 0.27, y: 0.60,
      description: 'Main entrance to Megaton.',
      image: 'img_0563.jpg' },
    { id: 151, name: 'Citadel Gate', category: 'doors', x: 0.61, y: 0.71,
      description: 'Entrance to the Brotherhood of Steel Citadel.',
      image: 'img_0567.jpg' },
    { id: 152, name: 'Tenpenny Tower Entrance', category: 'doors', x: 0.09, y: 0.81,
      description: 'Front gate of Tenpenny Tower.',
      image: 'img_0570.jpg' },
    { id: 153, name: 'Rivet City Bridge', category: 'doors', x: 0.71, y: 0.77,
      description: 'Retractable bridge entrance to Rivet City.',
      image: 'img_0575.jpg' }
];

// Collectibles data
const collectibles = {
    bobbleheads_special: [
        { id: 'bb_str', name: 'Strength Bobblehead', x: 0.27, y: 0.61, location: 'Megaton - Lucas Simms House',
          description: '+1 Strength permanently. Found in Lucas Simms\' house on a desk.' },
        { id: 'bb_per', name: 'Perception Bobblehead', x: 0.55, y: 0.62, location: 'Vault-Tec HQ',
          description: '+1 Perception permanently. On a desk in the CEO offices.' },
        { id: 'bb_end', name: 'Endurance Bobblehead', x: 0.61, y: 0.35, location: 'Deathclaw Sanctuary',
          description: '+1 Endurance permanently. In the back of the Deathclaw Sanctuary.' },
        { id: 'bb_cha', name: 'Charisma Bobblehead', x: 0.23, y: 0.58, location: 'Vault 108',
          description: '+1 Charisma permanently. In the cloning lab of Vault 108.' },
        { id: 'bb_int', name: 'Intelligence Bobblehead', x: 0.72, y: 0.78, location: 'Rivet City - Science Lab',
          description: '+1 Intelligence permanently. On Dr. Li\'s desk in the science lab.' },
        { id: 'bb_agi', name: 'Agility Bobblehead', x: 0.55, y: 0.45, location: 'Greener Pastures Disposal',
          description: '+1 Agility permanently. In the office of the disposal site.' },
        { id: 'bb_lck', name: 'Luck Bobblehead', x: 0.62, y: 0.72, location: 'Arlington Cemetery North',
          description: '+1 Luck permanently. In the basement of Arlington House.' }
    ],
    bobbleheads_skills: [
        { id: 'bb_barter', name: 'Barter Bobblehead', x: 0.18, y: 0.72, location: 'Evergreen Mills',
          description: '+10 Barter. In the back room of the bazaar.' },
        { id: 'bb_bigguns', name: 'Big Guns Bobblehead', x: 0.22, y: 0.10, location: 'Fort Constantine',
          description: '+10 Big Guns. In the CO quarters basement.' },
        { id: 'bb_energy', name: 'Energy Weapons Bobblehead', x: 0.15, y: 0.15, location: 'Raven Rock',
          description: '+10 Energy Weapons. On Colonel Autumn\'s desk.' },
        { id: 'bb_explosives', name: 'Explosives Bobblehead', x: 0.75, y: 0.35, location: 'WKML Broadcast Station',
          description: '+10 Explosives. In the sealed cistern.' },
        { id: 'bb_lockpick', name: 'Lockpick Bobblehead', x: 0.40, y: 0.58, location: 'Bethesda Ruins East',
          description: '+10 Lockpick. In the Bethesda Offices.' },
        { id: 'bb_medicine', name: 'Medicine Bobblehead', x: 0.23, y: 0.58, location: 'Vault 101',
          description: '+10 Medicine. In your father\'s desk.' },
        { id: 'bb_melee', name: 'Melee Weapons Bobblehead', x: 0.10, y: 0.92, location: 'Dunwich Building',
          description: '+10 Melee Weapons. In the virulent underchambers.' },
        { id: 'bb_repair', name: 'Repair Bobblehead', x: 0.58, y: 0.18, location: 'Aerefu',
          description: '+10 Repair. In Evan King\'s house.' },
        { id: 'bb_science', name: 'Science Bobblehead', x: 0.25, y: 0.24, location: 'Vault 106',
          description: '+10 Science. In the living quarters.' },
        { id: 'bb_smallguns', name: 'Small Guns Bobblehead', x: 0.68, y: 0.38, location: 'National Guard Depot',
          description: '+10 Small Guns. In the armory.' },
        { id: 'bb_sneak', name: 'Sneak Bobblehead', x: 0.58, y: 0.28, location: 'Yao Guai Tunnels',
          description: '+10 Sneak. Near the den entrance.' },
        { id: 'bb_speech', name: 'Speech Bobblehead', x: 0.42, y: 0.15, location: 'Paradise Falls',
          description: '+10 Speech. In Eulogy\'s pad.' },
        { id: 'bb_unarmed', name: 'Unarmed Bobblehead', x: 0.08, y: 0.45, location: 'Rockbreaker\'s Last Gas',
          description: '+10 Unarmed. In the back room.' }
    ],
    skillbooks: {
        barter: [
            { id: 'sb_barter1', name: 'Tales of a Junktown Jerky Vendor', x: 0.27, y: 0.61, location: 'Megaton - Craterside Supply' },
            { id: 'sb_barter2', name: 'Tales of a Junktown Jerky Vendor', x: 0.72, y: 0.78, location: 'Rivet City - Marketplace' }
        ],
        bigGuns: [
            { id: 'sb_bigguns1', name: 'U.S. Army: 30 Handy Flamethrower Recipes', x: 0.62, y: 0.72, location: 'The Citadel' }
        ],
        energyWeapons: [
            { id: 'sb_energy1', name: 'Nikola Tesla and You', x: 0.72, y: 0.78, location: 'Rivet City - Science Lab' }
        ],
        explosives: [
            { id: 'sb_explosives1', name: 'Duck and Cover!', x: 0.27, y: 0.61, location: 'Megaton - Common House' }
        ],
        lockpick: [
            { id: 'sb_lockpick1', name: 'Tumblers Today', x: 0.56, y: 0.58, location: 'Underworld' }
        ],
        medicine: [
            { id: 'sb_medicine1', name: 'D.C. Journal of Internal Medicine', x: 0.72, y: 0.78, location: 'Rivet City - Clinic' }
        ],
        meleeWeapons: [
            { id: 'sb_melee1', name: 'Grognak the Barbarian', x: 0.52, y: 0.55, location: 'Hubris Comics' }
        ],
        repair: [
            { id: 'sb_repair1', name: 'Dean\'s Electronics', x: 0.27, y: 0.61, location: 'Megaton - Craterside Supply' }
        ],
        science: [
            { id: 'sb_science1', name: 'Big Book of Science', x: 0.72, y: 0.78, location: 'Rivet City - Science Lab' }
        ],
        smallGuns: [
            { id: 'sb_smallguns1', name: 'Guns and Bullets', x: 0.62, y: 0.72, location: 'The Citadel' }
        ],
        sneak: [
            { id: 'sb_sneak1', name: 'Chinese Army: Special Ops Training Manual', x: 0.42, y: 0.15, location: 'Paradise Falls' }
        ],
        speech: [
            { id: 'sb_speech1', name: 'Lying, Congressional Style', x: 0.60, y: 0.62, location: 'Capitol Building' }
        ],
        unarmed: [
            { id: 'sb_unarmed1', name: 'Pugilism Illustrated', x: 0.08, y: 0.82, location: 'Tenpenny Tower' }
        ]
    }
};

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { CATEGORIES, COLLECTIBLE_CATEGORIES, locations, collectibles };
}
